sudo: false
dist: trusty
language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"
script:
 - yarn build
 - chmod +x ./ossutil64
 - ./ossutil64 config -e $OSS_ENDPOINT -i $OSS_ID -k $OSS_KEY
 - ./ossutil64 cp -r ./build oss://$OSS_BUCKETNAME_DEV/prod --update
 - ./ossutil64 cp -r ./build oss://$OSS_BUCKETNAME --update
 